[WIP] [2.6] PANDARIA: initial tke-operator
cnrancher/tke-operator pull request #2
Opened 2022-11-25 07:00 UTC by GGGitBoy

**Relate issue**
https://github.com/cnrancher/pandaria/issues/2558

2023-02-23 01:50 UTC, smallteeths commented on controller/tke-cluster-config-handler.go
> +	upstreamSpec := &tkev1.TKEClusterConfigSpec{}
我有个问题， 这个参数 cluster *tkeapi.Cluster 在 rancher 里调用 BuildUpstreamClusterState 时，是不是也需要用到 tke 的 sdk TKEClient.GetCluster(config.Spec.ClusterId) 来获取当前这个 tke cluster ？

2023-02-23 01:56 UTC, GGGitBoy commented on controller/tke-cluster-config-handler.go
> +	upstreamSpec := &tkev1.TKEClusterConfigSpec{}
这里传进来的 cluster、nodePools 就是通过 sdk 调用的，把这部分作为传参是因为想直接复用之前已经获取到的 cluster、nodePools 内容

2023-02-23 02:08 UTC, smallteeths commented on controller/tke-cluster-config-handler.go
> +	upstreamSpec := &tkev1.TKEClusterConfigSpec{}
> 这里传进来的 cluster、nodePools 就是通过 sdk 调用的，把这部分作为传参是因为想直接复用之前已经获取到的 cluster、nodePools 内容

我得想法是 tke-operator 是可以单独更新的。但是如果需要从 rancher 代码里当前依赖的 sdk 获得集群再传过来。有可能会出现 tke-operator sdk 更新了而 rancher 中依赖的 sdk 没有更新的情况。所以我建议是这种 sdk 获得集群最好统一在 tke-operator 里获得。

2023-02-23 02:33 UTC, smallteeths approved these changes
LGTM

2023-02-23 02:45 UTC, smallteeths commented on controller/tke-cluster-config-handler.go
> +	upstreamSpec := &tkev1.TKEClusterConfigSpec{}
我想错了在 rancher 调用的时候始终是调用旧的 tke-operator 依赖的包，即使单独更新了 tke-operator 也没有办法改变 BuildUpstreamClusterState 中的调用。我没有问题了谢谢

2023-02-23 03:37 UTC, Jason-ZW requested changes
Others LGTM

2023-02-23 03:37 UTC, Jason-ZW commented on go.mod
> +	github.com/rancher/wrangler v0.8.10
这个 `wrangler` 的版本 `v0.8.10` 的引入依据是？貌似跟 RPM 依赖版本不同

2023-02-23 03:37 UTC, Jason-ZW commented on go.mod
> +	github.com/rancher/wrangler-api v0.6.1-0.20200427172631-a7c2f09b783e
同理

2023-02-23 03:37 UTC, Jason-ZW commented on pkg/apis/tke.pandaria.io/v1/doc.go
> +Copyright 2019 Wrangler Sample Controller Authors
2023？

2023-02-23 03:37 UTC, Jason-ZW commented on pkg/apis/tke.pandaria.io/v1/types.go
> +Copyright 2017 The Kubernetes Authors.
2023？

2023-02-23 03:37 UTC, Jason-ZW commented on utils/parse.go
> +	tkeapi "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tke/v20180525"
format packages import order

2023-02-23 03:37 UTC, Jason-ZW commented on Dockerfile.dapper
> +RUN curl -sLf https://storage.googleapis.com/golang/go1.17.8.linux-${ARCH}.tar.gz | tar -xzf - -C /usr/local/
1.17 版本跟RPM GC中使用的版本不同，是否考虑 1.19？

2023-02-23 03:37 UTC, Jason-ZW commented on controller/tke-cluster-config-handler.go
> +	"time"
format package import order

2023-02-23 03:37 UTC, Jason-ZW commented on pkg/apis/tke.pandaria.io/v1/types.go
> +	ClusterId               string                   `json:"clusterId,omitempty"`
按照RPM命名规范 `clusterId` 最好可以统一成 `clusterID`

2023-02-23 03:37 UTC, Jason-ZW commented on pkg/apis/tke.pandaria.io/v1/types.go
> +	SubnetId            string `json:"subnetId,omitempty"`
同样问题

2023-02-23 03:37 UTC, Jason-ZW commented on driver/client/tke.go
> +	tkeapi "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tke/v20180525"
format package import order

2023-02-23 03:37 UTC, Jason-ZW commented on controller/tke-cluster-config-handler.go
> +}
这个指数退避是默认值不可调整么？如果只是为了删除集群的话应该是可以接受。如果其他地方也复用了那可能需要评估下

2023-02-23 07:28 UTC, GGGitBoy commented on go.mod
> +	github.com/rancher/wrangler v0.8.10
用的是当时 eks-operator 使用的版本。已更新

2023-02-23 07:29 UTC, GGGitBoy commented on controller/tke-cluster-config-handler.go
> +}
只在删除集群使用

2023-02-23 07:30 UTC, GGGitBoy commented
其他内容已更新。该仓库需要加到 drone ci 中

2023-02-24 01:48 UTC, Jason-ZW commented
Drone 已经开启

2023-02-24 01:48 UTC, Jason-ZW approved these changes
LGTM

2023-02-24 01:49 UTC, merged